export const styles = {
  green50: '#F1F8E9',
  green100: '#DCEDC8',
  green200: '#C5E1A5',
  green300: '#AED581',
  green400: '#9CCC65',
  green500: '#8BC34A',
  green600: '#7CB342',
  green700: '#689F38',
  green800: '#558B2F',
  green900: '#33691E',
  greenA100: '#CCFF90',
  greenA200: '#B2FF59',
  greenA400: '#76FF03',
  greenA700: '#64DD17',
  bootstrapGreen: '#28a745',
  red: '#C62828',
  greyTableRow: '#f2f2f2',
  greyTableBorder: '#e2e6e9',
  shadow: '#888888',
  borderRadius: '5px',
  blueInputFocus: 'rgba(0, 127, 255, 0.25)',
  inputBorderColor: 'rgba(0, 0, 0, 0.15)',
  reactSelectOptionColor: '#383838',
  modalStyle: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 400,
    bgcolor: 'background.paper',
    borderRadius: '5px',
    boxShadow: 24,
    p: 4,
  },
};

export const messages = {
  PB_NOT_SIGNED_IN: 'Please sign in to see your personal bests.',
  SD_NOT_SIGNED_IN: 'Please sign in to see your speed data.',
  SKILL_NOT_SIGNED_IN: 'Please sign in to see your freestyle skills.',
  IG_NOT_SIGNED_IN: 'Please sign in to see your Instagram inspiration.',
  NOTLEARNT_SKILLS_EMPTY: 'No skills to learn... Add some above!',
  LEARNT_SKILLS_EMPTY: 'Have not learnt any skills, jiayou!',
  PB_EMPTY: 'Nothing to display, start by entering a new speed record above.',
  SD_EMPTY: 'Nothing to display, start by entering a new personal best above.',
  SKILLS_EMPTY: 'Nothing to display, start by adding some skills above.',
  IG_EMPTY: 'Nothing to display, start by adding some posts above.',
};
